manifest:
  remotes:
    - name: solodros
      url-base: https://github.com/solodros
  projects:
    - name: zmk
      remote: solodros
      revision: ps2
      import: app/west.yml
  self:
    path: config
